### ISSUE TITLE
Suggestion: Vertical grid view

### ISSUE THREAD

**Issue by Jacksaur** [TigraTT-Driver/neoretro-dark#21]
This has very quickly became my new favorite Pegasus theme. The dark colour scheme and vertical Console posters are really unique.
That said, I find that the horizontally focused Game view makes it difficult to navigate through consoles that have large libraries. Could it be possible to add a vertically focused view, with more rows on display at once?
One similar to the design in the [Homage Theme](https://user-images.githubusercontent.com/30796598/62833647-a10a7480-bc85-11e9-9b1e-e7c5cfe9dec4.png) would be great, but even just a toggle to hide the details and screenshot area would be enough.

**Comment by TigraTT-Driver** [comment]
From the solution approach I would have tried a vertically mirrored variant of the layout of Homage: Gamegrid on the left, video / boxart (depending on view) remains on the top right and the game info is then displayed below this. As threshold for changing the display I would have used the existing setting "Game grid - viewable rows" again. If this is greater than 2, your suggestion is used. just have to see if I can get this to work so modular :smile:

**Comment by TigraTT-Driver** [comment]
It's now on my testing branch if you want to try it. So far, even my portable gaming device could handle a 6x5 grid with screenshot view very well. But probably some weak android devices will struggle / have higher loading times while scrolling through the grid

**Comment by Jacksaur** [comment]
Looks absolutely perfect. I love that the details fit into the collection's accent colour too!
The spacing between each game is a bit large on my screen, but I can mess with that myself.
Thanks!

**Comment by TigraTT-Driver** [comment]
you're using boxart for the grid items?
The spacing between the items can largly differ depending on the size of the used boxart and the items per row setting. Probably the best solution for this problem would be dynamicly set the items per row depending on the dimensions of the boxart like the pegasus default grid theme does.

**Comment by TigraTT-Driver** [comment]
Perfect :smile: I don't have a Switch collection but probalby PSP is also as bad.  I've put the changes now on master.
